spring.application.name=purchase
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=diwakar
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.security.user.name=diwakar
spring.security.user.password=diwakar